[tool.poetry]
name = "Anlasser"
version = "0.1.0"
description = ""
authors = ["Aljoscha Vollmerhaus <git@aljoscha.vollmerhaus.net>"]
readme = "README.md"
packages = [{include = "anlasser", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.test]
optional = true
[tool.poetry.group.test.dependencies]
pytest-mock = "^3.14.0"
pytest = "^8.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
anlasser-ctl = 'anlasser.client_cli:client_cli'
anlasser-agent = 'anlasser.agent_cli:agent_cli'
anlasser-mkvm = 'anlasser.mkvm_cli:mkvm_cli'
